from __future__ import annotations

import re
from typing import Any, Dict, List, Tuple, Optional, DefaultDict, Literal, Union
from pathlib import Path
from dataclasses import dataclass, field

from src.world.clock import Clock, TimeState, Stage
from src.utils import parse_kv_args


def make_activity_id(
    activity_type: str,
    time: TimeState,
    identifier: str,
) -> str:
    """Generate a unified activity ID.

    Format: {type}-{time}-{identifier}
    - time uses TimeState.__str__() format (e.g., Y2024-W05-activity-D2)
    - identifier is sanitized (spaces to underscores, keeps alphanumeric + CJK)

    Examples:
        - public-Y2024-W05-activity-D2-Cooking_Class
        - joint-Y2024-W05-activity-D2-Alice-dinner
        - encounter-Y2024-W05-activity-D2-Alice-Bob
        - solo-Y2024-W05-activity-D3-Bob
        - public-Y2024-W05-activity-D2-Gaokao_Math_Lecture
    """
    # Sanitize identifier: replace spaces with underscores, keep alphanumeric + CJK + _-
    clean_id = re.sub(r"[^\w\u4e00-\u9fff-]", "_", identifier.replace(" ", "_"))
    clean_id = re.sub(r"_+", "_", clean_id).strip("_")

    return f"{activity_type}-{time}-{clean_id}"


# Type alias for eligible_participants: "all" or list of character names
EligibleParticipants = Union[str, List[str]]


@dataclass
class PublicEvent:
    """Public event generated by the God Model (open-topic gathering).

    Public Activity is an "individual sign-up, parallel participation, no interaction"
    activity type, distinct from Joint Activity (friend-arranged, direct interaction).

    An event can be one-off or repeat across multiple weeks (same day each week).
    """

    event_id: str  # unique identifier, format: f"public-{year}-W{week:02d}-{index}"
    event_name: str  # event name, e.g. "Cooking Class"
    start_year: int  # year the event starts
    start_week: int  # week number the event starts
    start_day: int  # day of the week the event occurs (1-n_days)
    repeat_weeks: int  # duration in weeks (1 = one-off, >1 = repeats weekly)
    description: str  # event description
    eligible_participants: EligibleParticipants = "all"  # "all" or list of character names

    @property
    def start_t(self) -> TimeState:
        """Return the event time as a TimeState.

        Note: events passed to agents are "this-week instances" with start_year/start_week
        already set to the current week, so start_t is the activity time for this week.
        Even for repeating events, agents must sign up individually each week.
        """
        return TimeState(
            year=self.start_year,
            week=self.start_week,
            stage=Stage.ACTIVITY,
            day=self.start_day,
        )

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a dict."""
        return {
            "event_id": self.event_id,
            "event_name": self.event_name,
            "start_year": self.start_year,
            "start_week": self.start_week,
            "start_day": self.start_day,
            "repeat_weeks": self.repeat_weeks,
            "description": self.description,
            "eligible_participants": self.eligible_participants,
        }

    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "PublicEvent":
        """Deserialize from a dict."""
        return PublicEvent(
            event_id=d["event_id"],
            event_name=d["event_name"],
            start_year=d["start_year"],
            start_week=d["start_week"],
            start_day=d["start_day"],
            repeat_weeks=d.get("repeat_weeks", 1),
            description=d["description"],
            eligible_participants=d.get("eligible_participants", "all"),
        )

    def is_active_on(
        self, year: int, week: int, day: int, n_weeks_per_year: int
    ) -> bool:
        """Return True if the event is running on the given year/week/day.

        Args:
            year: Target year.
            week: Target week number.
            day: Target day number.
            n_weeks_per_year: Weeks per year (from config["world"]["time"]["n_week"]).
        """
        if day != self.start_day:
            return False
        # Compute weeks elapsed since the event started
        weeks_since_start = (year - self.start_year) * n_weeks_per_year + (
            week - self.start_week
        )
        return 0 <= weeks_since_start < self.repeat_weeks

    def is_active_this_week(self, year: int, week: int, n_weeks_per_year: int) -> bool:
        """Return True if the event is running during the given week (day-agnostic)."""
        weeks_since_start = (year - self.start_year) * n_weeks_per_year + (
            week - self.start_week
        )
        return 0 <= weeks_since_start < self.repeat_weeks

    def is_eligible(self, agent_name: str) -> bool:
        """Return True if the agent is eligible to participate in this event.

        Args:
            agent_name: The agent's name.

        Returns:
            True if agent_name is in eligible_participants or eligible_participants is "all".
        """
        if self.eligible_participants == "all":
            return True
        if isinstance(self.eligible_participants, list):
            return agent_name in self.eligible_participants
        return False  # unknown format — deny by default


@dataclass
class Schedule:
    """Unified activity record (single source of truth).

    Supports four activity types:
    - joint: multi-person activity (negotiated during the contact phase)
    - solo: single-person activity
    - public: open event / interest class (signed up during the position application phase)
    - encounter: spontaneous event / chance meeting (generated by the system after finalize_contact)

    activity_id is optional; if not provided, __post_init__ auto-generates it based on type:
    - joint:     {type}-{time}-{proposer}-{activity_name}
    - public:    {type}-{time}-{activity_name}
    - encounter: {type}-{time}-{p1}-{p2}
    - solo:      {type}-{time}-{participant}

    Note: to stay consistent with DataManager._append_jsonl's create-time behavior, the
    "time" field on disk is still injected by _append_jsonl and represents create_time.
    The activity_time field here represents when the activity occurs; it intentionally
    avoids reusing the name create_time to prevent semantic confusion with _append_jsonl.
    """

    # Required fields (no default)
    activity_name: str
    activity_time: TimeState  # strongly-typed activity time
    participants: List[str]

    # Type with default
    type: Literal["joint", "solo", "public", "encounter"] = "joint"

    # Optional fields
    activity_id: Optional[str] = None  # Auto-generated if not provided
    status: Literal["created", "canceled", "failed"] = "created"
    proposer: Optional[str] = None  # required for joint activity, optional otherwise
    actions: Optional[Dict[str, str]] = None  # required for joint activity, optional otherwise
    location: Optional[str] = None
    invited: List[str] | None = None
    required_participants: List[str] | None = None
    cancel_reason: Optional[str] = None
    proposal: Optional[str] = None
    event_description: Optional[str] = None  # Public Activity description
    # Creation time (injected by _append_jsonl, read by from_dict, not written by to_dict)
    time: Optional[TimeState] = None

    def __post_init__(self) -> None:
        """Auto-generate activity_id if not provided."""
        if self.activity_id is not None:
            return

        # Generate identifier based on type
        if self.type == "joint":
            if not self.proposer:
                raise ValueError("joint activity requires proposer for ID generation")
            identifier = f"{self.proposer}-{self.activity_name}"
        elif self.type == "public":
            identifier = self.activity_name
        elif self.type == "encounter":
            if len(self.participants) < 2:
                raise ValueError("encounter requires at least 2 participants")
            identifier = f"{self.participants[0]}-{self.participants[1]}"
        elif self.type == "solo":
            if not self.participants:
                raise ValueError("solo activity requires at least 1 participant")
            identifier = self.participants[0]
        else:
            raise ValueError(f"Unknown activity type: {self.type}")

        self.activity_id = make_activity_id(self.type, self.activity_time, identifier)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to a persistence-friendly dict."""
        return {
            "activity_id": self.activity_id,
            "activity_name": self.activity_name,
            "activity_time": str(self.activity_time),
            "participants": list(self.participants),
            "type": self.type,
            "status": self.status,
            **({"proposer": self.proposer} if self.proposer else {}),
            **({"actions": dict(self.actions)} if self.actions else {}),
            **({"location": self.location} if self.location else {}),
            **({"invited": list(self.invited)} if self.invited else {}),
            **(
                {"required_participants": list(self.required_participants)}
                if self.required_participants
                else {}
            ),
            **({"cancel_reason": self.cancel_reason} if self.cancel_reason else {}),
            **({"proposal": self.proposal} if self.proposal else {}),
            **(
                {"event_description": self.event_description}
                if self.event_description
                else {}
            ),
        }

    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "Schedule":
        """Strict deserialization: missing required fields or type mismatches raise immediately.

        Only used to read records written internally by Schedule.to_dict — no lenient cleaning.
        If you need to handle dirty external data, write a separate normalize function at the
        I/O boundary rather than relaxing the constraints here.
        """
        # 1) Required field presence
        try:
            activity_id = d["activity_id"]
            activity_name = d["activity_name"]
            activity_time_s = d["activity_time"]
            participants = d["participants"]
        except KeyError as e:
            raise ValueError(f"Schedule missing required field: {e.args[0]}")

        # 2) Basic type validation (strict — no implicit str()/list()/dict() coercion)
        if not isinstance(activity_id, str) or not activity_id:
            raise ValueError("Schedule.activity_id must be a non-empty str")
        if not isinstance(activity_name, str) or not activity_name:
            raise ValueError("Schedule.activity_name must be a non-empty str")
        if not isinstance(activity_time_s, str) or not activity_time_s:
            raise ValueError(
                "Schedule.activity_time must be a non-empty str (TimeState string)"
            )
        if not isinstance(participants, list):
            raise ValueError("Schedule.participants must be a list")

        # 3) Optional fields: proposer, actions (required for joint, optional for others)
        proposer = d.get("proposer")
        if proposer is not None and not isinstance(proposer, str):
            raise ValueError("Schedule.proposer must be a str when present")

        actions = d.get("actions")
        if actions is not None and not isinstance(actions, dict):
            raise ValueError("Schedule.actions must be a dict when present")

        # 4) Other optional fields (light constraints)
        typ = d.get("type", "joint")
        if typ not in ("joint", "solo", "public", "encounter"):
            raise ValueError(
                f"Schedule.type must be one of joint/solo/public/encounter, got: {typ}"
            )

        status = d.get("status", "created")
        if status not in ("created", "canceled", "failed"):
            raise ValueError(
                f"Schedule.status must be one of created/canceled/failed, got: {status}"
            )

        invited = d.get("invited")
        if invited is not None and not isinstance(invited, list):
            raise ValueError("Schedule.invited must be a list when present")

        req = d.get("required_participants")
        if req is not None and not isinstance(req, list):
            raise ValueError(
                "Schedule.required_participants must be a list when present"
            )

        cancel_reason = d.get("cancel_reason")
        if cancel_reason is not None and not isinstance(cancel_reason, str):
            raise ValueError("Schedule.cancel_reason must be a str when present")

        proposal = d.get("proposal")
        if proposal is not None and not isinstance(proposal, str):
            raise ValueError("Schedule.proposal must be a str when present")

        event_description = d.get("event_description")
        if event_description is not None and not isinstance(event_description, str):
            raise ValueError("Schedule.event_description must be a str when present")

        # Parse creation time if present (injected by _append_jsonl)
        time_str = d.get("time")
        creation_time = TimeState.from_string(time_str) if time_str else None

        return Schedule(
            activity_name=activity_name,
            activity_time=TimeState.from_string(activity_time_s),
            participants=participants,
            type=typ,  # type: ignore[arg-type]
            activity_id=activity_id,
            status=status,  # type: ignore[arg-type]
            proposer=proposer,
            actions=actions,
            location=(d.get("location") or None),
            invited=invited,  # type: ignore[list-item]
            required_participants=req,  # type: ignore[list-item]
            cancel_reason=cancel_reason,
            proposal=proposal,
            event_description=event_description,
            time=creation_time,
        )

    def format_activity_background(self) -> str:
        """Render a concise background string describing this activity.

        - Joint: include name, time, proposer, participants, and each person's
          action/proposal if present.
        - Solo: include name and time only.
        """

        assert self.status == "created"

        # Sort by name to ensure deterministic prompt for cache stability
        # Note: Encounter activities may not have actions set
        if self.actions:
            scheduling_process_str = "\n".join(
                [
                    f"- {who}: {str(act).strip()}"
                    for who, act in sorted(self.actions.items())
                ]
            )
        else:
            scheduling_process_str = ""

        lines: List[str] = [
            "## Current Activity\n",
            f"Joint Activity: {self.activity_name}",
            f"Current Time: {self.activity_time}",
            (f"Proposer: {self.proposer}" if self.proposer else ""),
            f"Participants: {', '.join(self.participants)}",
            (f"Location: {self.location}" if self.location else ""),
            (
                f"Scheduling Process:\n{scheduling_process_str}"
                if scheduling_process_str
                else ""
            ),
            # Include scene description for encounter activities
            (f"\n## Scene\n{self.event_description}" if self.event_description else ""),
        ]

        return "\n".join([ln for ln in lines if ln])


class MessageCenter:
    """In-memory message hub (queue).

    - No persistence; only caches messages produced in the current phase.
    - add() appends raw dicts without processing or validation.
    - confirm_schedule() settles joint activities based on structured fields.
    """

    def __init__(
        self, *, world_name: str, clock: Clock, root: Optional[Path] = None
    ) -> None:
        self.world_name = world_name
        self.clock = clock
        self._msgs: List[Dict[str, Any]] = []
        # Settlement result always kept as { name: [activity_record, ...] }
        self._created_activities: List[Schedule] = []
        # System notifications produced this round, aggregated per person; in-memory only, not persisted.
        # Used to feed back anomalies to relevant characters during settlement
        # (e.g. a response that couldn't be matched to any proposal).
        # Notifications are plain strings, consistent with the errs style in RoleAgent.
        self._notifications: Dict[str, List[str]] = {}
        # person -> activities (same structure as _created_activities; for the new direct-return interface)
        self._person2activity: Dict[str, List[Schedule]] = {}

    def add(self, msg: Dict[str, Any]) -> None:
        """Append a raw message dict to queue."""
        # As required: no processing, no validation
        self._msgs.append(msg)

    @property
    def created_activities(self) -> List[Schedule]:
        """Return list of successfully created activities this week."""
        return self._created_activities

    def clear(self) -> None:
        """Clear messages and settlement cache for the current phase."""
        self._msgs.clear()
        self._created_activities.clear()
        self._notifications.clear()
        self._person2activity.clear()

    def confirm_schedule(
        self,
        existing_schedules: Optional[Dict[str, Dict[str, "Schedule"]]] = None,
    ) -> List[Schedule]:
        """Settle joint activities at the end of the CONTACT phase.

        Rules:
        - Message types: message / propose_joint_activity / respond_invitation / cancel_joint_activity.
        - propose/respond/cancel must include activity_name in the msg_center.
        - For the same invitation, only the last response from a character is kept.
        - If the proposer sends a cancel, the corresponding proposal is voided.
        - Per-character conflict check: for the same time slot, only the "last-sent" arrangement
          is kept; others have their decision set to no with a reason.
        - Activity creation condition: all required_participants say yes, and at least 1 person
          overall says yes (including the proposer's own decision).
        - id = f"{proposer}-{activity_name}-{time}".

        Args:
            existing_schedules: Optional dict mapping person -> activity_time -> Schedule.
                Used to detect conflicts with schedules created in previous weeks.
                If None, only intra-week conflicts are detected.

        Returns:
            List of successfully created activities this week (system-wide view).
            Each involved person can call get_scheduling_result(name) to get their own
            view, which includes canceled/failed records (not persisted to DataManager).
        """
        if existing_schedules is None:
            existing_schedules = {}

        # 1) Pre-process: build structured propose / respond / cancel lists --------
        def _parse_ts(s: str) -> TimeState:
            return TimeState.from_string(str(s))

        def _req_str(obj: Dict[str, Any], key: str) -> str:
            """Fetch required string-like field and validate non-empty."""
            v = str(obj[key]).strip()  # KeyError bubbles up as desired
            if not v:
                raise ValueError(f"empty field '{key}'")
            return v

        def _req_list(obj: Dict[str, Any], key: str) -> List[str]:
            """Fetch required list-like field; accept singletons."""
            raw = obj[key]  # KeyError bubbles up
            if raw is None:
                return []
            if isinstance(raw, list):
                out = [str(x).strip() for x in raw if str(x).strip()]
            else:
                s = str(raw).strip()
                out = [s] if s else []
            return out

        class _Proposal:
            __slots__ = (
                "proposer",
                "activity_name",
                "invited",
                "required",
                "activity_time",
                "msg_time",
                "canceled",
                "cancel_time",
                "self_decision",  # whether the proposer participates (can be set to no on conflict)
                "raw_action",  # original action string (for consistent error formatting upstream)
                "message",  # proposer's message text (optional)
                "location",  # location string (optional)
                "proposal",  # activity proposal description (optional)
            )

            def __init__(self, obj: Dict[str, Any]) -> None:
                """Normalize and validate a propose message from raw dict."""
                self.proposer = _req_str(obj, "from")
                self.activity_name = _req_str(obj, "activity_name")
                self.activity_time = _req_str(obj, "activity_time")
                self.msg_time = _req_str(obj, "time")
                # Only accept invited_persons; do not fall back to 'to'
                self.invited = _req_list(obj, "invited_persons")
                if not self.invited:
                    raise ValueError(
                        "propose_joint_activity requires non-empty invited_persons"
                    )
                self.required = _req_list(obj, "required_participants")
                self.canceled = False
                self.cancel_time = None  # type: Optional[str]
                self.self_decision = "yes"  # proposer participates by default
                # raw_action/message are optional (test or system-injected messages may omit them)
                self.raw_action = _req_str(obj, "raw_action")
                self.message = str(obj.get("message", ""))
                self.location = str(obj.get("location", "")).strip()
                self.proposal = str(obj.get("proposal", ""))

            @property
            def id(self) -> str:
                time = TimeState.from_string(self.activity_time)
                identifier = f"{self.proposer}-{self.activity_name}"
                return make_activity_id("joint", time, identifier)

        class _Response:
            __slots__ = (
                "responder",
                "proposer",
                "activity_name",
                "decision",
                "msg_time",
                "activity_time",
                "reason",
                "raw_action",
                "message",
            )

            def __init__(self, obj: Dict[str, Any]) -> None:
                """Normalize and validate a response message from raw dict."""
                self.responder = _req_str(obj, "from")
                self.proposer = _req_str(obj, "to")
                self.activity_name = _req_str(obj, "activity_name")
                decision = _req_str(obj, "decision").lower()
                if decision not in ("yes", "no"):
                    raise ValueError(f"respond_invitation bad decision: {decision}")
                self.decision = decision  # 'yes'|'no'
                self.msg_time = _req_str(obj, "time")
                self.activity_time = ""  # fill after matching
                # raw_action/message are optional
                self.raw_action = str(obj.get("raw_action", ""))
                self.message = str(obj.get("message", ""))

        proposals: List[_Proposal] = []
        responses_all: List[_Response] = []
        cancels: List[
            Tuple[str, str, str]
        ] = []  # (proposer, activity_name, cancel_msg_time)
        # Per-character system notifications (in-memory only); e.g. "response unmatched, ignored".
        notifications: DefaultDict[str, List[str]] = DefaultDict(list)

        for obj in self._msgs:
            typ = obj["type"]
            if typ == "propose_joint_activity":
                proposals.append(_Proposal(obj))

            elif typ == "respond_invitation":
                responses_all.append(_Response(obj))

            elif typ == "cancel_joint_activity":
                proposer = _req_str(obj, "from")
                an = _req_str(obj, "activity_name")
                msg_time = _req_str(obj, "time")
                cancels.append((proposer, an, msg_time))

        # Under concurrency, _msgs collection order is non-deterministic.
        # For cache determinism, use a full tie-breaker sort:
        # - proposals:  (msg_time, proposer, activity_name)
        # - responses:  (msg_time, responder, proposer, activity_name)
        # - cancels:    (msg_time, proposer, activity_name)
        proposals.sort(
            key=lambda p: (_parse_ts(p.msg_time), p.proposer, p.activity_name)
        )
        responses_all.sort(
            key=lambda r: (
                _parse_ts(r.msg_time),
                r.responder,
                r.proposer,
                r.activity_name,
            )
        )
        cancels.sort(key=lambda t: (_parse_ts(t[2]), t[0], t[1]))

        # 2) Build index for matching -----------------------------------------------
        # Constraint: the same (proposer, activity_name) may only appear once per week.
        # Duplicates are treated as an upstream (RoleAgent) constraint violation — raise immediately.
        prop_map: Dict[Tuple[str, str], _Proposal] = {}
        for p in proposals:
            key = (p.proposer, p.activity_name)
            if key in prop_map:
                raise RuntimeError(
                    f"duplicate propose_joint_activity by same proposer and activity_name: "
                    f"proposer={p.proposer}, activity_name={p.activity_name}"
                )
            prop_map[key] = p

        # 3) Handle cancels: if cancel_time >= propose_msg_time → cancel; otherwise raise
        for proposer, an, cancel_t in cancels:
            key = (proposer, an)
            p = prop_map.get(key)
            if p is None:
                raise RuntimeError(
                    f"cancel_joint_activity has no matching propose: proposer={proposer}, activity_name={an}"
                )
            ct = _parse_ts(cancel_t)
            if _parse_ts(p.msg_time) > ct:
                raise RuntimeError(
                    f"cancel_joint_activity earlier than any propose: proposer={proposer}, activity_name={an}"
                )
            p.canceled = True
            p.cancel_time = cancel_t

        # 4) Match responses to proposals -------------------------------------------
        # Prefer exact match: same (proposer, activity_name) and responder in invited.
        # Fallback: within the same proposer's proposals, pick the latest one before
        # respond_time that includes the responder.
        # For multiple responses from the same responder to the same proposal, keep only the last.
        responses_by_proposal: DefaultDict[_Proposal, Dict[str, _Response]] = (
            DefaultDict(dict)
        )

        # Build per-proposer proposal index for fallback matching (unique per activity_name; unsorted)
        proposer_map: DefaultDict[str, List[_Proposal]] = DefaultDict(list)
        for p in prop_map.values():
            proposer_map[p.proposer].append(p)

        def _match_response(resp: _Response) -> Optional[_Proposal]:
            key = (resp.proposer, resp.activity_name)
            rt = _parse_ts(resp.msg_time)
            # Try exact match first (unique proposal by same name)
            p = prop_map.get(key)
            # Response time must be strictly after proposal time (no same-instant concurrency)
            if (
                p is not None
                and _parse_ts(p.msg_time) < rt
                and (resp.responder in p.invited)
            ):
                return p
            # Fallback: within the same proposer's proposals, pick the latest one
            # where msg_time <= respond_time and responder is in invited
            arr = proposer_map.get(resp.proposer, [])
            best: Optional[_Proposal] = None
            best_t: Optional[TimeState] = None
            for cand in arr:
                ct = _parse_ts(cand.msg_time)
                if ct < rt and (resp.responder in cand.invited):
                    if best is None or best_t is None or ct > best_t:
                        best = cand
                        best_t = ct
            return best

        for r in responses_all:
            prop = _match_response(r)
            if prop is None:
                # No match: ignore this response and record a system notification for the responder
                notifications[r.responder].append(
                    f"Action: {r.raw_action}\nError: no matching propose_joint_activity found"
                )
                continue
            # Keep only the last response from this responder
            prev = responses_by_proposal[prop].get(r.responder)
            if prev is None or (
                _parse_ts(prev.msg_time) <= _parse_ts(r.msg_time)
                and not (
                    prev.activity_name == prop.activity_name
                    and r.activity_name != prop.activity_name
                )
            ):
                # Later overwrites earlier, unless later is a fuzzy match and earlier was exact
                responses_by_proposal[prop][r.responder] = r

        # 5) Conflict resolution: per character, keep only the "last-sent" arrangement
        #    for each activity_time slot.
        # Collect each character's "arrangement candidates":
        #  - their own non-canceled proposals (default yes; msg_time = proposal msg_time)
        #  - their yes responses to others' proposals (msg_time = response msg_time)
        per_person_by_time: DefaultDict[
            str, Dict[str, List[Tuple[str, str, object]]]
        ] = DefaultDict(dict)
        # value item: (kind, msg_time, holder) where kind in {"prop", "resp", "existing"};
        # holder is _Proposal, _Response, or Schedule
        for p in proposals:
            if p.canceled:
                continue
            per_person_by_time[p.proposer].setdefault(p.activity_time, []).append(
                ("prop", p.msg_time, p)
            )
        for p, resp_map in responses_by_proposal.items():
            if p.canceled:
                continue
            for resp in resp_map.values():
                if resp.decision == "yes":
                    resp.activity_time = p.activity_time
                    per_person_by_time[resp.responder].setdefault(
                        p.activity_time, []
                    ).append(("resp", resp.msg_time, resp))

        # 5b) Add existing cross-week schedules to conflict detection.
        # existing_schedules: person -> activity_time -> Schedule
        # Priority rules: joint > public > encounter; same type: first-come-first-served.
        #   - existing joint blocks new joint proposals (first-come-first-served)
        #   - existing public/encounter does NOT block new joint proposals (joint can override)
        for person, time2sched in existing_schedules.items():
            for act_time, sched in time2sched.items():
                # existing_joint: high priority, blocks new proposals
                # existing_lower: low priority (public/encounter), can be overridden by new joint
                kind = "existing" if sched.type == "joint" else "existing_lower"
                per_person_by_time[person].setdefault(act_time, []).append(
                    (kind, str(sched.time), sched)
                )

        # For each character at each specific time, keep the highest-priority candidate;
        # mark the rest as conflicts.
        # Remaining items in per_person_by_time are non-canceled proposals, yes responses,
        # or existing schedules.
        # Priority (highest wins): existing_joint > prop > resp > existing_lower(public/encounter)
        _CONFLICT_PRIORITY = {
            "existing_lower": 0,  # public/encounter can be overridden by joint
            "resp": 1,
            "prop": 2,
            "existing": 3,  # joint: first-come-first-served, cannot be overridden
        }
        for person, time_items in per_person_by_time.items():
            for plan_t, items in time_items.items():
                if len(items) <= 1:
                    continue

                def _sort_key(x: Tuple[str, str, object]) -> tuple:
                    kind, msg_time, _ = x
                    return (_CONFLICT_PRIORITY[kind], _parse_ts(msg_time))

                items.sort(key=_sort_key)
                keep_kind, keep_msg_t, keep_obj = items[-1]

                # Determine the winner description
                if keep_kind in ("existing", "existing_lower"):
                    keep_kind_word = "already scheduled"
                elif keep_kind == "resp":
                    keep_kind_word = "accepted"
                else:
                    keep_kind_word = "proposed"

                # All others: set to no + reason
                for kind, _mt, obj in items[:-1]:
                    if kind in ("existing", "existing_lower"):
                        # Existing schedules can't be modified; skip
                        continue
                    elif kind == "resp":
                        r: _Response = obj  # type: ignore[assignment]
                        r.decision = "no"
                        notifications[r.responder].append(
                            f"Action: {r.raw_action}\nError: decision automatically changed to 'no' due to time conflict with another activity '{keep_obj.activity_name}' that you have {keep_kind_word}."
                        )

                    elif kind == "prop":
                        p: _Proposal = obj  # type: ignore[assignment]
                        p.self_decision = "no"
                        notifications[p.proposer].append(
                            f"Action: {p.raw_action}\nError: activity automatically canceled due to time conflict with another activity '{keep_obj.activity_name}' that you have {keep_kind_word}."
                        )

        # 6) Produce per-character activity lists ----------------------------------
        _person2activity: Dict[str, List[Schedule]] = {}
        created_activities: List[Schedule] = []

        def _append(name: str, rec: Schedule) -> None:
            _person2activity.setdefault(name, []).append(rec)

        for p in proposals:
            # Canceled proposals: output cancel record for all parties;
            # individuals who had a conflict may receive a more specific reason
            if p.canceled:
                sched = Schedule(
                    activity_id=p.id,
                    activity_name=p.activity_name,
                    activity_time=TimeState.from_string(p.activity_time),
                    proposer=p.proposer,
                    participants=[],
                    actions={},
                    type="joint",
                    status="canceled",
                    location=(p.location or None),
                    invited=list(p.invited),
                    required_participants=list(p.required),
                    cancel_reason=f"canceled by proposer {p.proposer}",
                    proposal=p.proposal,
                )
                _append(p.proposer, sched)
                for person in p.invited:
                    _append(person, sched)
                continue

            # Collect each person's decision (no reply defaults to no)
            resp_map = responses_by_proposal[p]
            decisions: Dict[str, str] = {}
            for person in p.invited:
                r = resp_map.get(person)
                if r:
                    decisions[person] = r.decision
                else:
                    decisions[person] = "no"

            # Proposer's own decision
            proposer_decision = p.self_decision

            participants: List[str] = []
            if proposer_decision == "yes":
                participants.append(p.proposer)
            # Sort decisions.items() for deterministic participant order (cache stability)
            participants.extend(
                sorted([name for name, d in decisions.items() if d == "yes"])
            )

            # Activity creation condition
            required_missing = set(p.required) - set(participants)
            created = (
                (proposer_decision == "yes")
                and (len(required_missing) == 0)
                and len(participants) > 1
            )

            if created:
                # Sort resp_map.items() for deterministic actions_map key order (cache stability)
                actions_map = {
                    p.proposer: p.raw_action,
                    **{
                        name: resp.raw_action for name, resp in sorted(resp_map.items())
                    },
                }
                sched = Schedule(
                    activity_id=p.id,
                    activity_name=p.activity_name,
                    activity_time=TimeState.from_string(p.activity_time),
                    proposer=p.proposer,
                    participants=participants,
                    actions=actions_map,
                    type="joint",
                    status="created",
                    location=(p.location or None),
                    invited=list(p.invited),
                    required_participants=list(p.required),
                    proposal=p.proposal,
                )
                created_activities.append(sched)
                # Notify proposer and all invited of the created activity (visibility).
                # Whether it "takes effect" is determined upstream at persist time
                # based on membership (only participants are written to disk).
                _append(p.proposer, sched)
                for person in p.invited:
                    _append(person, sched)
            else:
                if required_missing:
                    reason = "required participants did not accept: " + ", ".join(
                        required_missing
                    )
                elif proposer_decision == "no":
                    reason = "the proposer canceled the activity for some reason"
                else:
                    reason = "no participants accepted"
                sched = Schedule(
                    activity_id=p.id,
                    activity_name=p.activity_name,
                    activity_time=TimeState.from_string(p.activity_time),
                    proposer=p.proposer,
                    participants=participants,
                    actions={},
                    type="joint",
                    status="failed",
                    location=(p.location or None),
                    invited=list(p.invited),
                    required_participants=list(p.required),
                    cancel_reason=reason,
                    proposal=p.proposal,
                )
                # Not created: output failed record to proposer and all invited (in-memory only, for feedback).
                _append(p.proposer, sched)
                for person in p.invited:
                    _append(person, sched)

        # Expose system notifications for this round
        self._notifications = dict(notifications)
        # New interface: expose person->activities directly
        self._person2activity = _person2activity
        self._created_activities = created_activities
        return created_activities

    def get_notifications(self, name: str) -> List[str]:
        """Return system notification strings produced for this character during confirm_schedule."""
        return self._notifications.get(name, []) or []

    def get_scheduling_result(self, name: str) -> List[Schedule]:
        """Return the activity records (Schedule objects) for this person.

        Note: only read during the finalize_contact phase to persist created records.
        """
        return self._person2activity.get(name, []) or []
